global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter-1'
    static_configs:
      - targets: ['node-exporter-1:9100']
        
  - job_name: 'node-exporter-2'
    static_configs:
      - targets: ['node-exporter-2:9100']
