apiVersion: 1

datasources:
  - name: #Name
    type: loki 
    access: proxy
    url: #http://you_instance_publicip:3100
    version: 1
    editable: false 
    isDefault: false
    
  - name: #Name
    type: loki 
    access: proxy
    url: #http://you_instance_publicip>:3100
    version: 1
    editable: false 
    isDefault: false

  - name: #Name
    type: prometheus
    access: proxy
    url: #http://your_prometheus_instance_publicip:9090
    version: 1
    editable: false 
    isDefault: false

  - name: #Name
    type: prometheus
    access: proxy
    url: #http://your_prometheus_instance_publicip:9090
    version: 1
    editable: false 
    isDefault: false

  - name: #name
    type: alertmanager
    access: proxy
    url: #http://your_alertmanager_instance_publicip:9093
    version: 1
    editable: false
    isDefault: false

  - name: #name
    type: alertmanager
    access: proxy
    url: #http://your_alertmanager_instance_publicip:9093
    version: 1
    editable: false
    isDefault: false
