apiVersion: 1

datasources:
  - name: #Name
    type: loki 
    access: proxy
    url: #http://<you_instance_publicip>[:3100]
    version: 1
    editable: false #or true
    isDefault: false
    
  - name: #Name
    type: loki 
    access: proxy
    url: #http://<you_instance_publicip>[:3100]
    version: 1
    editable: false #or true
    isDefault: false

  - name: #Name
    type: prometheus
    access: proxy
    url: #http://<your_prometheus_instance_publicip>[:9090]
    version: 1
    editable: false #or true
    isDefault: false

  - name: #Name
    type: prometheus
    access: proxy
    url: #http://<your_prometheus_instance_publicip>[:9090]
    version: 1
    editable: false #or true
    isDefault: false