apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://3.85.198.142:3100
    version: 1
    editable: false
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://54.91.205.161:3100
    version: 1
    editable: false
    isDefault: true